services:
  utalog-app:
    build: .
    container_name: utalog-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run prisma:migrate && npm run dev"
    environment:
      - NODE_ENV=development
    tty: true
